### ISSUE TITLE
ember install ember-sse not working

### ISSUE THREAD

**Issue by BennyAlex** [chauhraj/ember-sse#2]
when trying to install ember-sse, following error occurs: 

```Command failed: npm install --save-dev --loglevel error ember-sse
npm ERR! code E404
npm ERR! 404 Not Found: ember-sse@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bfranz\AppData\Roaming\npm-cache\_logs\2017-06-26T13_36_19_962Z-debug.log

Error: Command failed: npm install --save-dev --loglevel error ember-sse
npm ERR! code E404
npm ERR! 404 Not Found: ember-sse@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bfranz\AppData\Roaming\npm-cache\_logs\2017-06-26T13_36_19_962Z-debug.log

    at Promise.all.then.arr (C:\Users\bfranz\workspace\route-management\frontend\node_modules\execa\index.js:210:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by chauhraj** [comment]
Hi Ben,

I will take a look and get back to you.
